---
title: "Investment Simulations"
author: "Angel De Jesus Alcala Ruiz"
date: "2022-10-28"
output: html_document
---

```{r}
library(tidyverse)
library(cowplot)
```


```{r}
# Table of stock-bond composition

Stocks = seq(from = 0, to = 100, by = 5)
Bonds = seq(from = 100, to = 0., by = -5)
Avg_mu = c(0.0509,0.0540,0.0570,0.0600,0.0629,
           0.0657,0.0684,0.0711,0.0737,0.0762,
           0.0787,0.0811,0.0834,0.0856,0.0878,
           0.0899,0.0919,0.0938,0.0957,0.0974,0.0991)
SD_sigma = c(0.0403,0.0399,0.0411,0.0437,0.0474,
             0.0521,0.0574,0.0632,0.0694,0.0759,
             0.0825,0.0894,0.0964,0.1035,0.1107,
             0.1180,0.1254,0.1328,0.1403,0.1479,0.1555)

StockBondComp = data.frame(Stocks,Bonds,Avg_mu,SD_sigma)
```



```{r}
# Using indices to pull out the rate from table

#StockIndex = which(StockBondComp$Stocks == 20)
```


```{r}
#StockBondComp$Avg_mu[StockIndex]
```



```{r}
InvestmentSimulation = function(P = 1000,PMT = 360,n = 10,portolio_ratio = 100,Simulations = 50, Target_amount = 5000){
  #' @title InvestmentSimulation
  #' 
  #' @description This function computes an investment simulation
  #' 
  #' @params P (principal)
  #' @params PMT (periodic contributions)
  #' @params n (number of years)
  #' @params Simulations (number of years)
  #' 
  #' @return a data frame of simulations over n years 
  #'          with variable annual rates
  
  k = 1
  YEAR = c(0:n)
  NON_INVEST = c(P)
  non_invest_amount = P
  
  r = as.numeric(filter(select(StockBondComp,3), Stocks == portolio_ratio))
  sigma = as.numeric(filter(select(StockBondComp,4), Stocks == portolio_ratio))
  
  for (i in 1:n) {
    non_invest_amount = non_invest_amount + PMT
    NON_INVEST = c(NON_INVEST, non_invest_amount)
  }
  
  Invest_Table = data.frame(YEAR,NON_INVEST)
  
  for (simulation in 1:Simulations){
    amount0 = P
    SIM = c(P)
    for (year in 1:n) {
      rate = rnorm(1,mean = r, sd = sigma)
      amount1 = amount0*(1 + rate) + PMT
      SIM = c(SIM,amount1)
      amount0 = amount1
    }
    Invest_Table = data.frame(Invest_Table,SIM)
  }
  
  Average = Invest_Table %>%
    select(3:(Simulations + 2)) %>%
    rowMeans()
  
  Invest_Table = data.frame(Invest_Table,Average)
  
  OutPut = lst(Invest_Table,P,PMT,n,Simulations,Target_amount)
  
  return(OutPut)
}
```


```{r}
# Create Investment Data Frame

InvestmentLIST = InvestmentSimulation(P = 1000,PMT = 500,n = 4, portolio_ratio = 40,Simulations = 4,Target_amount = 2500)
InvestmentDF = InvestmentLIST[[1]]

# Find the number of columns and rows

number_of_cols = ncol(InvestmentDF)
number_of_rows = nrow(InvestmentDF)

# Change the name of the columns

HeaderName = c("YEAR","NON_INVEST",paste0("SIM",1:(InvestmentLIST$Simulations)),"AVERAGE")
colnames(InvestmentDF) = HeaderName
```

```{r}
pivotedInvestmentDF = pivot_longer(InvestmentDF, 
  cols = starts_with("sim"),
  names_to = "SIMULATIONS", 
  values_to = "AMOUNT")
```


```{r}
# Colors for our graph

blue = "#0080ff"
light_blue = "#4CA6FF"
red = "#FF4C4C"
gray = "#ADADAD"
yellow = "#FFA700"
orange = "#FF5300"

# For graphing purposes
#   - Find the column that contains max and min after the 10-year period

col_with_max = which(InvestmentDF == max(InvestmentDF[number_of_rows,3:(InvestmentLIST$Simulations + 2)]), arr.ind = TRUE)[2]
col_with_min = which(InvestmentDF == min(InvestmentDF[number_of_rows,3:(InvestmentLIST$Simulations + 2)]), arr.ind = TRUE)[2]

# For graphing purposes
#   - Find the quartiles after the 10-year period 

probs_for_quantiles = c(.25,.5,.75)
quantiles = quantile(InvestmentDF[number_of_rows,3:(InvestmentLIST$Simulations)],probs_for_quantiles)
```


```{r}
InvestmentPlot = ggplot(data = InvestmentDF) +
  labs(title = "Investment Simulation",
       subtitle = paste0(InvestmentLIST$Simulations," simulations with random annual rates,\nan initial investment of $", InvestmentLIST$P," and yearly contributions of $", InvestmentLIST$PMT),
       x = "Year",
       y = "Balance in U.S. $")  +
  scale_x_continuous(breaks = seq(0,InvestmentLIST$n,by = 1)) +
  theme(plot.margin = unit(c(.5,2,2.6,.5), "cm"),
        plot.title = element_text(size = 16),
        plot.subtitle = element_text(size = 12),
        axis.ticks = element_blank(),
        axis.line = element_line(color = gray),
        panel.background = element_blank(),
        panel.grid.major.y = element_line(color = gray,
                                          size = .2,
                                          linetype = "solid"),
        axis.text = element_text(size = 10)) +
  coord_cartesian(xlim = c(0,InvestmentLIST$n), ylim = c(0,max(InvestmentDF)), clip = "off") 

  for (i in 1:InvestmentLIST$Simulations){
    InvestmentPlot = InvestmentPlot +
      geom_line(aes_string(x = "YEAR",y = InvestmentDF[,i + 2]),
                color = light_blue,
                alpha = .2,
                size = .8)
  }

  InvestmentPlot = InvestmentPlot + 
   geom_line(aes(x = YEAR, y = AVERAGE),
             color = blue,
             size = .8,
             alpha = 1,
             linetype = "dashed") +
    geom_line(aes(x = YEAR, 
                 y = InvestmentDF[,col_with_max]),
            color = orange,
              size = .75,
              alpha = .8) + 
    geom_line(aes(x = YEAR, y = InvestmentDF[,col_with_min]),
              color = yellow, 
              size = .75,
              alpha = .8) +
    geom_hline(yintercept = InvestmentLIST$Target_amount,
             color = "black",
             linetype = "dashed")
  
InvestmentPlot = ggdraw(InvestmentPlot) +
  draw_label("Statistics at the end of the investment period:", x = .325, y = .19, size = 12) +
  draw_label("0th %ile (Min)", x = .15, y = .14, size = 11, color = yellow, fontface = "bold") +
  draw_label("25th %ile", x = .325, y = .14, size = 11) +
  draw_label("50th %ile", x = .5, y = .14, size = 11) +
  draw_label("75th %ile", x = .65, y = .14, size = 11) + 
  draw_label("100th %ile (Max)", x = .85, y = .14, size = 11, color = orange, fontface = "bold") +
  draw_label(paste0("$",round(min(InvestmentDF[number_of_rows,3:InvestmentLIST$Simulations]), digits = 2)),
             x = .15,
             y = .09,
             size = 11,
             color = yellow,
             fontface = "bold") +
  draw_label(paste0("$",round(quantiles[[1]], digits = 2)), 
             x = .325,
             y = .09,
             size = 11) +
  draw_label(paste0("$",round(quantiles[[2]], digits = 2)),
             x = .5,
             y = .09,
             size = 11) +
  draw_label(paste0("$",round(quantiles[[3]], digits = 2)),
             x = .65,
             y = .09,
             size = 11) + 
  draw_label(paste0("$",round(max(InvestmentDF[number_of_rows,3:InvestmentLIST$Simulations]), digits = 2)),
             x = .85,
             y = .09,
             size = 11,
             color = orange,
             fontface = "bold")

InvestmentPlot
```



```{r}
findPositition = function(x,value){
  #' @title findPosition
  #' @description this function finds the position of some value in some vector x
  #' @params x some vector
  #' @params value some value
  #' @return the two positions that value lies in x

  for (i in 1:(length(x) - 1)){
    if (between(value, x[i],x[i + 1])){
      xpos1 = i
      xpos2 = i + 1
    }
  }
  output = c(xpos1,xpos2)
  return(output)
}
```


```{r}
InvestmentDF
```
```{r}
InvestmentLIST$Target_amount
```


Let's now test code for probability graph

```{r}
YEAR = c(0:(InvestmentLIST$n))
PROPORTIONS = rep(0,InvestmentLIST$n + 1)
```

```{r}
InvestmentDF
```


```{r}
```


```{r} 
for (i in 1:(InvestmentLIST$n + 1)) {
  
  amounts_in_year = slice(select(InvestmentDF,3:(InvestmentLIST$Simulations + 2)),i)
  count = sum(amounts_in_year >= 2500)
  prob = count/(InvestmentLIST$Simulations)
  
  cat("----","\n")
  cat("i = ", i,"\n")
  cat("count = ", count,"\n")
  cat("prob = ", prob,"\n")
        
  PROPORTIONS[year] = prob
}
      
ProbabilityDF = data.frame(YEAR,PROPORTIONS)
```




```{r}
ggplot(data = ProbabilityDF) + geom_col(aes(x = YEAR, y = PROPORTIONS))
```
```{r}
pivotedInvestmentDF %>%
  group_by(YEAR) %>%
  summarise(MIN = min(AMOUNT),
            MAX = max(AMOUNT))
```


```{r}
InvestmentDF %>%
  group_by(YEAR) %>%
  summarise(
    count = sum(select(InvestmentDF,3:5) > NON_INVEST)
  )
```

```{r}
pivotedInvestmentDF %>%
  group_by(YEAR) %>%
  summarise(
    count = sum(AMOUNT > NON_INVEST)
  )
```


```{r}
select(filter(StockBondComp,Stocks == 45),3)
```
```{r}
as.numeric(select(filter(StockBondComp,Stocks == 45),3))

```


```{r}
dejesusalcala/shinyapps.io/investmentsimulator
```




